### ISSUE TITLE
Support for VIM?

### ISSUE THREAD

**Issue by perriv** [UMCTM/language-pml#1]
Any plans for creating a vim syntax package?

**Comment by dpastoor** [comment]
ha I think I'm the only one in the group that uses vim some (usually vim bindings in the IDE of choice) and no one in our industry will go near it, so answer - highly doubtful

**Comment by perriv** [comment]
Cool, but how many of these same people you reference use Atom? I really don't want to start a text editor war in this issue. Atom is clearly easier to pick-up and develop packages for, but there will be extremely relevant modeling scenarios in which a graphical environment is simply not accessible.

**Comment by dpastoor** [comment]
haha - the people, as of now literally use nothing. The most recent version of the phoenix gui text editor finally added some super basic things like bracket matching, but until then literally has been the equivalent of using notepad.

There's no reason not to come up with VIM syntax, but off the top of my head I don't think there is a convenient way of using .tmLanguage files that work in atom, sublime, and [ace](http://ace.c9.io/#nav=about) (should we embed something in a webapp). 

The choice of atom was it is free, open source/hackable, and easy to install cross platforms, but there is nothing inherently tying us to it, so down the line if there is interest from users that is definitely feasible. 

A run of thumb when thinking about new features, as crazy as it might sound, is if 'your' parents needed to use this tool, what would you give them to get them up and running - that is the level of technical competency to expect from >90% of users, no joke.

**Comment by perriv** [comment]
My use case still stands. Although I'm perfectly aware of the relative lack of technical skills of the community as a while, I think our target demographic is the technical subset that would sometimes prefer to stick to the command-line, especially in a server or Linux environment.

Anyway, just wanted to gauge interest...

**Comment by dpastoor** [comment]
So just to be clear, 'technical subset' in our community has a very different connotation than you are likely thinking of (keep this in mind not just for editor but for overall clip api).

Think of technical subset as people mostly copying and pasting pre-developed scripts and typing in the basic `execute ....`.

I would be surprised if, in our target demographic, more than 10 people have used vim beyond accidentally having it as the default editor and having to learn `:wq` to save a quick change.

The 'only' people technically inclined enough and vim consistently (which I would bet money is <10) would likely be deeply entrenched in their workflows with nonmem and probably not interested.

The closest you'd get to people using an editor in the command-line is `emacs` since some plugins like emacs-speaks-statistics used to be used to work with R/etc, but again, those people will be highly tied to nonmem and unlikely to have any interest in budging.

@vjd did anyone at Uppsala (on an average likely the most technical group in the world) use VIM?

**Comment by dpastoor** [comment]
to also put some background that might help - very few/no people in our field come from technical (in the IT/computational sense) - they are usually engineers, statisticians, or clinicians with some mathematical inclination. As such, most people are familiar with excel, matlab, or SAS, with R becoming more and more popular in the last number of years. So being 'technically competent' would be more suggestive of "can write a basic R script or SAS code rather than do it in excel". Command line usage often stops at `ls pwd less ...", and, for example, people using tools like version control is virtually unheard of.

This is compounded by the fact that in most large companies, data processing and modeling are done by separate people, so the modelers will say I need the dataset to look like x,y,z and a programmer will shape that data and provide it as a CSV file. 

Smaller companies where people do the actual munging will again be constrained to R/SAS, which neither has required much command line usage.

Finally, those that do have IT backgrounds but have some interest in the work in the field, as you have, gravitate towards building tools, and thus would also not necessarily have the inclination to put energy into running many models beyond testing. 

Hopefully this helps paint a picture, so to speak, of the typical 'technically competent' person. When targeting the other crowd, I am not kidding when I say, think of your/someone's parents using this, and that will be the level of comfort/confidence.

If you have any more questions about the typical user personas let me know.

**Comment by perriv** [comment]
Thanks for your input, Devin.
